#########################################################
# Description : summons the splinter arrows generated by the Splintering enchantment.
# Creators : reNemesic
#########################################################


# note : do not remove the positioned ^ ^ ^ part of the executes, it is necessary since "anchored eyes" forces you to use caret notation
$execute as @s anchored eyes positioned ^ ^ ^ run summon arrow ~$(x1) ~$(y1) ~$(z1) {Motion:[$(dx1)d, $(dy1)d, $(dz1)d]}
$execute as @s anchored eyes positioned ^ ^ ^ run summon arrow ~$(x2) ~$(y2) ~$(z2) {Motion:[$(dx2)d, $(dy2)d, $(dz2)d]}
$execute as @s anchored eyes positioned ^ ^ ^ run summon arrow ~$(x3) ~$(y3) ~$(z3) {Motion:[$(dx3)d, $(dy3)d, $(dz3)d]}